# ============================================================
# DS / DA / BA SPECIALIZATION: PYTHON (30 Dedicated Questions: Order 1-30)
# ============================================================

DEPARTMENT = "DA/DS/BA - Python"
DEPARTMENTS = [
    "DA/DS/BA - Python",
    "DS/DA/BA - Python",
    "DA/DS/BA (Python)",
    "DS/DA/BA (Python)",
    "DA/DS/BA - Python Technical",
    "DS/DA/BA - Python Technical",
]

questions = [
    # Questions 1–10: Python Basics and Data Types
    {
        "order": 1,
        "question": "What is the output of this code?\n\nx = 10\ny = 3\nprint(x // y)",
        "options": [
            "3.33",
            "3",
            "4",
            "1",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 2,
        "question": "What is the output?\n\nx = \"5\"\ny = 2\nprint(x * y)",
        "options": [
            "10",
            "55",
            "52",
            "TypeError",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 3,
        "question": "What is the output?\n\nprint(type(10 / 2))",
        "options": [
            "<class 'int'>",
            "<class 'float'>",
            "<class 'double'>",
            "<class 'number'>",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 4,
        "question": "What is the output?\n\nx = [1, 2, 3]\nprint(x[-1])",
        "options": [
            "1",
            "2",
            "3",
            "-1",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 5,
        "question": "What is the output?\n\nprint(bool(\"\"))",
        "options": [
            "True",
            "False",
            "None",
            "Error",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 6,
        "question": "What is the output?\n\nx = 10\nx += 5\nx *= 2\nprint(x)",
        "options": [
            "20",
            "25",
            "30",
            "40",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 7,
        "question": "What is the output?\n\nprint(2 ** 3 ** 2)",
        "options": [
            "64",
            "512",
            "256",
            "36",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 8,
        "question": "What is the output?\n\nx = \"Python\"\nprint(x[1:4])",
        "options": [
            "Pyt",
            "yth",
            "ytho",
            "tho",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 9,
        "question": "What is the output?\n\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(x)",
        "options": [
            "[1, 2, 3]",
            "[1, 2, 3, 4]",
            "[4, 1, 2, 3]",
            "[1, 2, 4]",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 10,
        "question": "What is the output?\n\nprint(10 == 10.0)",
        "options": [
            "True",
            "False",
            "10",
            "TypeError",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    # Questions 11–20: Loops, Conditions and Functions
    {
        "order": 11,
        "question": "What is the output?\n\nfor i in range(1, 5):\n    print(i, end=\" \")",
        "options": [
            "1 2 3 4 5",
            "1 2 3 4",
            "0 1 2 3 4",
            "0 1 2 3",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 12,
        "question": "What is the output?\n\nx = 7\nif x > 5:\n    print(\"A\")\nelif x > 3:\n    print(\"B\")\nelse:\n    print(\"C\")",
        "options": [
            "A",
            "B",
            "C",
            "A B",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 13,
        "question": "What is the output?\n\ntotal = 0\nfor i in range(1, 4):\n    total += i\nprint(total)",
        "options": [
            "3",
            "4",
            "6",
            "10",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 14,
        "question": "What is the output?\n\nx = 5\nwhile x > 2:\n    print(x, end=\" \")\n    x -= 1",
        "options": [
            "5 4 3 2",
            "5 4 3",
            "4 3 2",
            "5 4",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 15,
        "question": "What is the output?\n\ndef add(a, b=2):\n    return a + b\n\nprint(add(5))",
        "options": [
            "5",
            "2",
            "7",
            "10",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 16,
        "question": "What is the output?\n\ndef test():\n    x = 10\n\nprint(test())",
        "options": [
            "10",
            "0",
            "False",
            "None",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 17,
        "question": "What is the output?\n\nx = [10, 20, 30, 40]\nprint(x[1:3])",
        "options": [
            "[10, 20, 30]",
            "[20, 30]",
            "[20, 30, 40]",
            "[10, 20]",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 18,
        "question": "What is the output?\n\nfor i in range(5):\n    if i == 3:\n        break\n    print(i, end=\" \")",
        "options": [
            "0 1 2",
            "0 1 2 3",
            "1 2 3",
            "0 1 2 4",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 19,
        "question": "What is the output?\n\nfor i in range(5):\n    if i == 2:\n        continue\n    print(i, end=\" \")",
        "options": [
            "0 1 2 3 4",
            "0 1 3 4",
            "1 2 3 4",
            "0 1",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 20,
        "question": "What is the output?\n\ndef square(x):\n    return x * x\n\nprint(square(3) + square(2))",
        "options": [
            "13",
            "25",
            "36",
            "10",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    # Questions 21–30: Lists, Dictionaries, Strings and Exceptions
    {
        "order": 21,
        "question": "What is the output?\n\nnums = [1, 2, 3]\nprint(nums + [4, 5])",
        "options": [
            "[1, 2, 3, 9]",
            "[5, 7, 3]",
            "[1, 2, 3, 4, 5]",
            "TypeError",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 22,
        "question": "What is the output?\n\nnums = [10, 20, 30]\nnums.insert(1, 15)\nprint(nums)",
        "options": [
            "[10, 20, 15, 30]",
            "[10, 15, 20, 30]",
            "[15, 10, 20, 30]",
            "[10, 20, 30, 15]",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 23,
        "question": "What is the output?\n\nx = {1, 2, 2, 3, 3, 3}\nprint(len(x))",
        "options": [
            "6",
            "5",
            "3",
            "1",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 24,
        "question": "What is the output?\n\ndata = {\"a\": 10, \"b\": 20}\nprint(data.get(\"c\", 30))",
        "options": [
            "None",
            "0",
            "30",
            "KeyError",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 25,
        "question": "What is the output?\n\ntext = \"Python\"\nprint(text[::-1])",
        "options": [
            "Python",
            "nohtyP",
            "Pnohty",
            "nothPy",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 26,
        "question": "What is the output?\n\nx = [1, 2, 3]\nresult = x.pop()\nprint(result, x)",
        "options": [
            "1 [2, 3]",
            "3 [1, 2]",
            "3 [1, 2, 3]",
            "None [1, 2]",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 27,
        "question": "What is the output?\n\nprint(len(\"Python\") + len([1, 2, 3]))",
        "options": [
            "6",
            "3",
            "9",
            "18",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 28,
        "question": "What is the output?\n\nx = [1, 2, 3]\ny = x.copy()\ny.append(4)\nprint(len(x), len(y))",
        "options": [
            "4 4",
            "3 4",
            "3 3",
            "4 3",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 29,
        "question": "What is the output?\n\ntry:\n    print(10 / 0)\nexcept ZeroDivisionError:\n    print(\"Error\")",
        "options": [
            "0",
            "10",
            "Error",
            "ZeroDivisionError",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 30,
        "question": "What is the output?\n\na = [1, 2, 3, 4, 5]\nresult = [x for x in a if x % 2 == 0]\nprint(result)",
        "options": [
            "[1, 3, 5]",
            "[2, 4]",
            "[1, 2, 3, 4, 5]",
            "[0, 2, 4]",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
