# ============================================================
# DS / DA / BA SPECIALIZATION: MYSQL (30 Dedicated Questions: Order 1-30)
# ============================================================

DEPARTMENT = "DA/DS/BA - MySQL"
DEPARTMENTS = [
    "DA/DS/BA - MySQL",
    "DA/DS/BA - My SQL",
    "DA/DS/BA - SQL",
    "DS/DA/BA - MySQL",
    "DS/DA/BA - My SQL",
    "DS/DA/BA - SQL",
    "DA/DS/BA (MySQL)",
    "DS/DA/BA (MySQL)",
    "MySQL",
    "My SQL",
]

questions = [
    {
        "order": 1,
        "question": "Which query retrieves employees whose salary is greater than 50,000?",
        "options": [
            "SELECT * FROM employees WHERE salary > 50000;",
            "SELECT * FROM employees HAVING salary > 50000;",
            "SELECT * FROM employees GROUP BY salary > 50000;",
            "SELECT * FROM employees ORDER BY salary > 50000;",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 2,
        "question": "Which function counts all rows in a table, including rows containing NULL values?",
        "options": [
            "SUM(*)",
            "COUNT(*)",
            "COUNT(column_name)",
            "TOTAL(*)",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 3,
        "question": "Which clause filters grouped results based on an aggregate condition?",
        "options": [
            "WHERE",
            "ORDER BY",
            "HAVING",
            "GROUP BY",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 4,
        "question": "If a salary column contains 10 rows, of which 3 are NULL, what does COUNT(salary) return?",
        "options": [
            "10",
            "7",
            "3",
            "0",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 5,
        "question": "Which query sorts employees by salary from highest to lowest?",
        "options": [
            "SELECT * FROM employees ORDER BY salary ASC;",
            "SELECT * FROM employees GROUP BY salary DESC;",
            "SELECT * FROM employees ORDER BY salary DESC;",
            "SELECT * FROM employees SORT BY salary DESC;",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 6,
        "question": "Which constraint uniquely identifies each row and does not permit NULL values?",
        "options": [
            "UNIQUE",
            "NOT NULL",
            "FOREIGN KEY",
            "PRIMARY KEY",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 7,
        "question": "Which command removes a table along with its structure?",
        "options": [
            "DELETE TABLE students;",
            "DROP TABLE students;",
            "TRUNCATE DATABASE students;",
            "REMOVE TABLE students;",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 8,
        "question": "Which command removes all rows but preserves the table structure?",
        "options": [
            "DROP TABLE employees;",
            "DELETE DATABASE employees;",
            "TRUNCATE TABLE employees;",
            "REMOVE FROM employees;",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 9,
        "question": "Which operator checks whether a value matches any value in a specified list?",
        "options": [
            "BETWEEN",
            "IN",
            "LIKE",
            "EXISTS",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 10,
        "question": "Which condition selects names beginning with the letter A?",
        "options": [
            "WHERE name LIKE '%A';",
            "WHERE name LIKE '_A%';",
            "WHERE name LIKE 'A%';",
            "WHERE name LIKE '%A%';",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 11,
        "question": "Which join returns only rows with matching values in both tables?",
        "options": [
            "LEFT JOIN",
            "CROSS JOIN",
            "INNER JOIN",
            "RIGHT JOIN",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 12,
        "question": "Which join returns every row from the left table, even when there is no match in the right table?",
        "options": [
            "RIGHT JOIN",
            "LEFT JOIN",
            "INNER JOIN",
            "CROSS JOIN",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 13,
        "question": "Which keyword removes duplicate rows from query results?",
        "options": [
            "UNIQUE",
            "DISTINCT",
            "DIFFERENT",
            "SINGLE",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 14,
        "question": "Which expression returns 0 when salary is NULL?",
        "options": [
            "IFNULL(salary, 0)",
            "NULLIF(salary, 0)",
            "IFNULL(0, salary)",
            "COUNT(salary, 0)",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 15,
        "question": "Which command modifies the structure of an existing table?",
        "options": [
            "UPDATE TABLE",
            "CHANGE TABLE",
            "ALTER TABLE",
            "MODIFY DATABASE",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 16,
        "question": "Which command changes existing values in table rows?",
        "options": [
            "ALTER",
            "UPDATE",
            "MODIFY",
            "REPLACE TABLE",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 17,
        "question": "Which clause groups employees who belong to the same department?",
        "options": [
            "ORDER BY department",
            "HAVING department",
            "GROUP BY department",
            "DISTINCT department",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 18,
        "question": "Which aggregate function returns the highest salary?",
        "options": [
            "TOP(salary)",
            "UPPER(salary)",
            "MAX(salary)",
            "HIGH(salary)",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 19,
        "question": "Which function calculates the average of non-NULL salary values?",
        "options": [
            "MEAN(salary)",
            "AVG(salary)",
            "AVERAGE(salary)",
            "MID(salary)",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 20,
        "question": "Which condition correctly checks for NULL department values?",
        "options": [
            "WHERE department = NULL",
            "WHERE department == NULL",
            "WHERE department IS NULL",
            "WHERE department EQUALS NULL",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 21,
        "question": "What is the primary purpose of a foreign key?",
        "options": [
            "To ensure unique values in every column",
            "To enforce referential integrity between tables",
            "To sort records automatically",
            "To prevent all duplicate rows in a table",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 22,
        "question": "Which statement adds an email column to the students table?",
        "options": [
            "UPDATE TABLE students ADD email VARCHAR(100);",
            "ALTER TABLE students ADD COLUMN email VARCHAR(100);",
            "MODIFY TABLE students CREATE email VARCHAR(100);",
            "INSERT INTO students COLUMN email VARCHAR(100);",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 23,
        "question": "Which query retrieves the first five rows from a table in MySQL?",
        "options": [
            "SELECT * FROM employees LIMIT 5;",
            "SELECT TOP 5 * FROM employees;",
            "SELECT * FROM employees FETCH 5;",
            "SELECT * FROM employees FIRST 5;",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 24,
        "question": "Which statement correctly inserts a row into students(name, age)?",
        "options": [
            "ADD INTO students VALUES ('Ravi', 21);",
            "INSERT students(name, age) VALUES ('Ravi', 21);",
            "INSERT INTO students (name, age) VALUES ('Ravi', 21);",
            "UPDATE students SET name='Ravi', age=21;",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 25,
        "question": "Which condition selects salaries between 30,000 and 60,000, including both endpoints?",
        "options": [
            "salary BETWEEN 30000 AND 60000",
            "salary BETWEEN 30000 TO 60000",
            "salary IN 30000 AND 60000",
            "salary >= 30000 OR salary <= 60000",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 26,
        "question": "What does COUNT(DISTINCT department) count?",
        "options": [
            "All employee rows",
            "Unique non-NULL department values",
            "All department values, including duplicates",
            "Only NULL department values",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 27,
        "question": "Which operator combines results from two compatible SELECT queries and removes duplicates?",
        "options": [
            "JOIN",
            "UNION ALL",
            "UNION",
            "MERGE",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 28,
        "question": "Which query retrieves employees whose salary equals the maximum salary in the table?",
        "options": [
            "SELECT * FROM employees WHERE salary = MAX(salary);",
            "SELECT * FROM employees WHERE salary = (SELECT MAX(salary) FROM employees);",
            "SELECT * FROM employees HAVING salary = MAX(salary);",
            "SELECT MAX(salary) FROM employees WHERE salary = salary;",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 29,
        "question": "Which command permanently saves changes made in a transaction?",
        "options": [
            "SAVEPOINT",
            "ROLLBACK",
            "COMMIT",
            "BEGIN",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 30,
        "question": "Which query retrieves employees whose salary is greater than the overall average salary?",
        "options": [
            "SELECT * FROM employees WHERE salary > AVG(salary);",
            "SELECT * FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);",
            "SELECT * FROM employees HAVING salary > AVG(salary);",
            "SELECT * FROM employees GROUP BY salary > AVG(salary);",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
