# ============================================================
# HTML / CSS / JAVASCRIPT APTITUDE TEST
# 30 Dedicated Technical Multiple Choice Questions (Order 1-30)
# ============================================================

DEPARTMENTS = [
    "HTML / CSS / JavaScript",
    "Python Full Stack - Front End",
    "Java Full Stack - Front End",
    "Python Full Stack - Frontend",
    "Java Full Stack - Frontend",
    "Front End",
    "Frontend",
    "HTML",
    "CSS",
    "JavaScript",
    "Web Development"
]

questions = [
    {
        "order": 1,
        "question": "What does 'HTML' stand for?",
        "options": [
            "Hyper Tool Multi Language",
            "Hyper Text Markup Language",
            "High Text Markup Language",
            "Hyper Transfer Markup Link",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 2,
        "question": "Which tag creates the largest heading on a webpage?",
        "options": [
            "<h6>",
            "<head>",
            "<h1>",
            "<heading>",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 3,
        "question": "Which CSS property changes the color of text?",
        "options": [
            "font-color",
            "color",
            "text-color",
            "background-text",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 4,
        "question": "Which symbol is used for an ID selector in CSS?",
        "options": [
            ". (dot)",
            "* (asterisk)",
            "& (ampersand)",
            "# (hash)",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 5,
        "question": "Which JavaScript keyword declares a variable that cannot be reassigned?",
        "options": [
            "var",
            "let",
            "const",
            "static",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 6,
        "question": "Which HTML tag is used to create a hyperlink?",
        "options": [
            "<a>",
            "<link>",
            "<href>",
            "<url>",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 7,
        "question": "Which method prints output to the browser console?",
        "options": [
            "print()",
            "console.log()",
            "echo()",
            "document.print()",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 8,
        "question": "Which attribute of the <img> tag specifies the image path?",
        "options": [
            "href",
            "link",
            "src",
            "path",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 9,
        "question": "Which CSS property changes the size of text?",
        "options": [
            "text-size",
            "font-style",
            "font-size",
            "size",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 10,
        "question": "Which JavaScript operator checks both value and data type?",
        "options": [
            "=",
            "==",
            "===",
            "!=",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 11,
        "question": "Which CSS declaration turns an element into a flex container?",
        "options": [
            "display: flex;",
            "flex: container;",
            "position: flex;",
            "layout: flexbox;",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 12,
        "question": "What does 'box-sizing: border-box' do?",
        "options": [
            "Adds margin to the width",
            "Includes padding and border in the element's width",
            "Removes the border",
            "Ignores the padding",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 13,
        "question": "What is the output? console.log(typeof null);",
        "options": [
            "\"null\"",
            "\"undefined\"",
            "\"object\"",
            "\"number\"",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 14,
        "question": "Which HTML5 semantic tag is used for navigation links?",
        "options": [
            "<navigate>",
            "<menu-bar>",
            "<links>",
            "<nav>",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 15,
        "question": "Which array method returns a new array containing only the elements that pass a test?",
        "options": [
            "filter()",
            "map()",
            "forEach()",
            "find()",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 16,
        "question": "An element with 'position: absolute' is positioned relative to what?",
        "options": [
            "Always the <body>",
            "The nearest positioned ancestor",
            "Its parent (always)",
            "The browser window only",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 17,
        "question": "What does document.querySelector('.box') return?",
        "options": [
            "An array of all '.box' elements",
            "The first matching element",
            "The last '.box' element",
            "A Boolean value",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 18,
        "question": "Which event name fires when a user clicks a button (used with addEventListener)?",
        "options": [
            "press",
            "tap",
            "click",
            "select",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 19,
        "question": "What is the output? console.log(2 + \"3\");",
        "options": [
            "5",
            "\"23\"",
            "NaN",
            "Error",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 20,
        "question": "Which has the highest priority in CSS specificity (without !important)?",
        "options": [
            "Element selector (p)",
            "Class selector (.box)",
            "ID selector (#box)",
            "Inline style (style=\"...\")",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 21,
        "question": "What is the output?\nfunction outer() {\n  let c = 0;\n  return function () { return ++c; };\n}\nconst f = outer();\nf();\nconsole.log(f());",
        "options": [
            "1",
            "2",
            "0",
            "undefined",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 22,
        "question": "What is the order of the output?\nconsole.log('A');\nsetTimeout(() => console.log('B'), 0);\nPromise.resolve().then(() => console.log('C'));\nconsole.log('D');",
        "options": [
            "A B C D",
            "A D B C",
            "A C D B",
            "A D C B",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 23,
        "question": "Which method creates a new function with 'this' permanently bound to a given object?",
        "options": [
            "call()",
            "apply()",
            "bind()",
            "assign()",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 24,
        "question": "What is the output?\nconsole.log(x);\nvar x = 5;",
        "options": [
            "5",
            "undefined",
            "ReferenceError",
            "null",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 25,
        "question": "What does 'grid-template-columns: repeat(3, 1fr);' do?",
        "options": [
            "Creates 3 rows of equal height",
            "Creates 3 equal-width columns",
            "Creates 3 columns of 1px each",
            "Repeats the grid 3 times",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 26,
        "question": "Event delegation is based on which concept?",
        "options": [
            "Event capturing only",
            "Event bubbling",
            "Event cancelling",
            "Event emitting",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 27,
        "question": "What is the output?\nconsole.log([1, 2, 3].reduce((a, b) => a + b, 10));",
        "options": [
            "6",
            "16",
            "10",
            "123",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 28,
        "question": "What is the difference between 'defer' and 'async' on a <script> tag?",
        "options": [
            "They are exactly the same",
            "defer runs in order after HTML parsing; async runs as soon as the file is downloaded",
            "async runs in order after HTML parsing; defer runs as soon as the file is downloaded",
            "defer works only for inline scripts",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 29,
        "question": "What is the output?\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
        "options": [
            "0 1 2",
            "3 3 3",
            "2 2 2",
            "undefined x3",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 30,
        "question": "In Promise.all([p1, p2, p3]), what happens if one promise rejects?",
        "options": [
            "It waits for all promises to finish",
            "It ignores the rejected promise",
            "It rejects immediately with the first rejection reason",
            "It returns only the resolved values",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
