# ============================================================
# MECHANICAL ENGINEERING - PTC CREO (3D CAD)
# 40 Dedicated CAD & Mechanical Aptitude Questions
# ============================================================

DEPARTMENT = "MECH - Creo"

questions = [
    {
        "order": 1,
        "question": "Which tool we used to split a single line into two or more lines?",
        "options": [
            "Corner",
            "Split",
            "Divide",
            "Cuts",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 2,
        "question": "Which option used to find the sketch was overdrawn?",
        "options": [
            "Highlight a open ends",
            "Shaded colors",
            "Overlapping geomentry",
            "Reference",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 3,
        "question": "Why we untick the 'use default template'?",
        "options": [
            "to draw the drawing directly",
            "to select the proper unit template",
            "to use the dimensions autolock",
            "to use inlbs-part-solid-abs template",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 4,
        "question": "What is concentric Circle?",
        "options": [
            "Make in number of circles by using one centre",
            "Make a circle tanget",
            "Make two circles",
            "All of the Above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 5,
        "question": "Which short key we used in creo to form a drawing in isometric view?",
        "options": [
            "Ctrl+G",
            "Ctrl+H",
            "Ctrl+D",
            "Ctrl+I",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 6,
        "question": "What is the default angle of counter sunk head?",
        "options": [
            "118 Degree",
            "90 Degree",
            "45 Degree",
            "100 Degree",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 7,
        "question": "If we create a single line and extrude it, How it make a profile at self?",
        "options": [
            "Solid",
            "Surface",
            "Circular",
            "Spring",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 8,
        "question": "If 10 circles are in different dimensions, which tool we used for make it same as every circle?",
        "options": [
            "Parallel",
            "Perpendicular",
            "Equal",
            "Symmentry",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 9,
        "question": "Which of the following used to connect open ends?",
        "options": [
            "Corner",
            "Project",
            "Offset",
            "Pattern",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 10,
        "question": "How do make a single line dimension If it shows two or more?",
        "options": [
            "By using coincident",
            "By using Tanget",
            "By using Perpendicular",
            "All of the Above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 11,
        "question": "In assembly, if the assembled part as completed, which helps to understand our assembly is properly assembled?",
        "options": [
            "Fully Defined",
            "Dactily Constrained",
            "Fully Constrained",
            "Fully Constrained using assumption",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 12,
        "question": "Where we find the default shapes like, Polygon, Arcs, Stars?",
        "options": [
            "Shapes Generator",
            "Pallet",
            "Tool Bars",
            "Modify tools",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 13,
        "question": "How to hide a plane temporary?",
        "options": [
            "Go to Datum Display filters",
            "Select the plane and Create",
            "View manager",
            "Refit",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 14,
        "question": "Which of these tools are we not used in creo?",
        "options": [
            "Extrude",
            "Stifner",
            "Revolve",
            "Shell",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 15,
        "question": "What is the previous name of CREO?",
        "options": [
            "Fiqua",
            "Pro/E",
            "Ansa",
            "Inventor",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 16,
        "question": "Which option used to orient the sketching plane parallel to plane?",
        "options": [
            "lefit",
            "saved orientation",
            "sketch view",
            "display style",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 17,
        "question": "What is line Tangent?",
        "options": [
            "Make a line tangent to a circle",
            "Make two circles tangent together",
            "Make a line tangent to two circle",
            "Make single tangent line",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 18,
        "question": "How many sides are in Hexagon?",
        "options": [
            "6",
            "5",
            "8",
            "10",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 19,
        "question": "Which is Regenerative command?",
        "options": [
            "Ctrl+G",
            "Ctrl+H",
            "Ctrl+D",
            "Ctrl+I",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 20,
        "question": "In Pallete, how many profiles we take in one time?",
        "options": [
            "3",
            "2",
            "4",
            "1",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 21,
        "question": "Which option used to find the lines over drawn?",
        "options": [
            "Over lapping geomentry",
            "Highlight Open ends",
            "Shade closed loops",
            "None of the above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 22,
        "question": "Which of the below tools not used for form a solid shape?",
        "options": [
            "Extrude",
            "Revolve",
            "Sweep",
            "Shell",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 23,
        "question": "How to convert the surface body as solid body?",
        "options": [
            "By Using extrude",
            "Make of as capped ends",
            "Use solidify",
            "Convert to solid",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 24,
        "question": "What is trajectory in sweep or swept blend?",
        "options": [
            "centre line or arc of the profile",
            "Orgin",
            "Defined shape object",
            "None of the above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 25,
        "question": "What is Co-axial?",
        "options": [
            "Same axis Alignment",
            "Axis of circular profile",
            "Midpoint of rectangular profile",
            "Edge of the rectangular profile",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 26,
        "question": "How do we create sphere shape?",
        "options": [
            "Extrude",
            "Revolve",
            "Sweep",
            "Blend",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 27,
        "question": "How many types of fillets exists in creo 2D?",
        "options": [
            "4",
            "3",
            "5",
            "2",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 28,
        "question": "Which centre line used to create a revolved object?",
        "options": [
            "centreline in sketching area",
            "Pattern centre line",
            "Construction mode line",
            "None of the above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 29,
        "question": "Which of the following option we used create a view of the model to our need?",
        "options": [
            "Re-orient",
            "view normal",
            "Default orientation",
            "Repaint",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 30,
        "question": "Why its not possible for make swept blend by using only one trajectory :-",
        "options": [
            "Swept blend needs two orgins",
            "Swept blend only needs one orgins and multi trajectories",
            "Swept blend only use when the drawing has multi corners",
            "All of the above",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 31,
        "question": "Which of these two option are not shown in editing tools unless we select the entities?",
        "options": [
            "Mirror & rotate , resize",
            "Corner & divide",
            "Modify & delete segment",
            "Rotate & mirror & resize",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 32,
        "question": "In thread type standard hole, the term UNC'S full form is __________?",
        "options": [
            "Universal National Convention",
            "United Nations Command",
            "Unified National Course",
            "United National Pitch thread",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 33,
        "question": "Is it possible to mirror a body in 3D?",
        "options": [
            "Yes",
            "No",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 34,
        "question": "How to make a solid part angle on both side?",
        "options": [
            "By Using add taper",
            "By Using Draft",
            "By Using shell",
            "By Using extrude",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 35,
        "question": "Which of the following tool used for make spring?",
        "options": [
            "Sweep",
            "Revolve",
            "Rotational blend",
            "Helical sweep",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 36,
        "question": "Do we need path in blend to create a profile?",
        "options": [
            "Yes",
            "No",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 37,
        "question": "Full form of inlbs.",
        "options": [
            "inches pounds",
            "inches lenght breath sec",
            "inches line base scale",
            "inches sec",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 38,
        "question": "Which Template we used in CREO for drawing?",
        "options": [
            "inlbs-part-solid-abs",
            "mmns-part-solid-sel",
            "mmns-harns-solid-abs",
            "mmns-part-solid-abs",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 39,
        "question": "How many Constrain tools in CREO?",
        "options": [
            "Four",
            "Six",
            "Ten",
            "Nine",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
    {
        "order": 40,
        "question": "Which of these option used to make a Hollow out the inside of a solid?",
        "options": [
            "Hole",
            "Draft",
            "Thicken",
            "Shell",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - Creo", "MECH", "Creo"],
    },
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
