# ============================================================
# MECHANICAL (CREO / 3D CAD) QUESTIONS (Orders 1 - 30)
# ============================================================

MECH_DEPARTMENTS = ["MECH - Creo", "MECH"]

questions = [
    {
        "order": 1,
        "question": "What is PTC Creo primarily categorized as in engineering design?",
        "options": [
            "Operating system kernel utility",
            "Parametric 3D CAD / CAM / CAE modeling software",
            "Relational Database Management System",
            "Vector graphic illustration software"
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 2,
        "question": "In Creo Sketcher, what is the key difference between 'Weak' and 'Strong' dimensions?",
        "options": [
            "Weak dimensions are measured in inches; Strong dimensions are measured in millimeters",
            "Weak dimensions apply only to 3D solids; Strong dimensions apply to 2D sketches",
            "Weak dimensions are automatically generated by the Intent Manager; Strong dimensions are explicitly defined or modified by the user",
            "Weak dimensions cannot be seen on screen; Strong dimensions are always visible"
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 3,
        "question": "Which tool in Creo is used to create a 3D solid by linearly projecting a 2D sketch perpendicular to the sketch plane?",
        "options": [
            "Sweep",
            "Extrude",
            "Revolve",
            "Blend"
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 4,
        "question": "What essential geometric reference is mandatory when creating a solid feature using the 'Revolve' tool in Creo?",
        "options": [
            "A spherical datum coordinate",
            "A helical trajectory curve",
            "A centerline / Axis of revolution",
            "A chamfer vertex point"
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 5,
        "question": "What is the primary function of a 'Datum Plane' in Creo parametric modeling?",
        "options": [
            "Defines the raw material cost of the component",
            "Serves as a reference plane for sketching, dimensioning, and feature placement",
            "Specifies the thermal conductivity of the alloy",
            "Renders photorealistic raytraced textures"
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 6,
        "question": "Which tool in Creo creates a solid feature by sweeping a planar cross-section along an open or closed trajectory path?",
        "options": [
            "Shell",
            "Hole",
            "Extrude",
            "Sweep"
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 7,
        "question": "What is the engineering purpose of applying a 'Round' (Fillet) to the re-entrant corners of a mechanical part?",
        "options": [
            "To reduce stress concentrations and eliminate notch effects",
            "To speed up 3D printing slicing",
            "To increase the structural weight of the casting",
            "To make the CAD file size smaller"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 8,
        "question": "Which dimension scheme option is available when defining a standard 'Chamfer' in Creo?",
        "options": [
            "Diameter x Pitch only",
            "45 x D, D x D, D1 x D2, and Angle x D",
            "Volume x Density",
            "Radius x Arc Length only"
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 9,
        "question": "In Creo, which feature is used to hollow out the interior of a solid body while maintaining specified wall thickness?",
        "options": [
            "Shell",
            "Rib",
            "Draft",
            "Mirror"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 10,
        "question": "Why is a 'Draft' feature applied to faces of components designed for plastic injection molding or metal casting?",
        "options": [
            "To increase the hardness of the plastic resin",
            "To prevent oxidation of the mold steel",
            "To convert 3D geometry into 2D drawing lines",
            "To provide a taper angle allowing easy ejection of the part from the mold"
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 11,
        "question": "Which Creo feature is specifically engineered for adding structural stiffening webs between intersecting walls?",
        "options": [
            "Datum Axis",
            "Extrude Cut",
            "Rib (Profile Rib / Trajectory Rib)",
            "Chamfer"
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 12,
        "question": "What are the standard hole creation types provided by the Creo 'Hole' tool?",
        "options": [
            "Magnetic and Hydraulic",
            "Simple, Standard (Threaded/Clearance), and Sketched",
            "Punched and Laser cut only",
            "Square, Hexagonal, and Octagonal only"
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 13,
        "question": "Which pattern type in Creo allows replicating features radially around a central cylindrical axis?",
        "options": [
            "Fill Pattern",
            "Table Pattern",
            "Direction Pattern",
            "Axis Pattern"
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 14,
        "question": "In Creo, what capability do 'Relations' (Tools > Relations) provide in parametric modeling?",
        "options": [
            "Mathematical equations that drive dimensions based on other dimensions or parameters",
            "Email notifications when a file is saved",
            "Bluetooth connections to CNC machines",
            "Automatic color grading of 3D models"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 15,
        "question": "What is a 'Family Table' in Creo used for?",
        "options": [
            "Managing user accounts and employee salaries",
            "Arranging color palettes in the rendering module",
            "Generating a collection of similar parts (instances) derived from a single generic model",
            "Organizing computer hard drive directories"
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 16,
        "question": "In Creo Assembly, which constraint aligns two planar faces so that their normal vectors point in opposite directions and touch?",
        "options": [
            "Align",
            "Mate",
            "Orient",
            "Insert"
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 17,
        "question": "Which Creo Assembly constraint is commonly used to assemble a bolt or pin into a cylindrical hole in one step?",
        "options": [
            "Insert",
            "Tangent",
            "Fix",
            "Parallel"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 18,
        "question": "In Creo Mechanism Design, which connection joint allows pure rotational movement around a single axis (1 degree of freedom)?",
        "options": [
            "Slider joint",
            "Ball joint",
            "Cylinder joint",
            "Pin joint"
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 19,
        "question": "What tool in Creo Assembly is utilized to identify physical overlapping between neighboring solid components?",
        "options": [
            "Explode State animation",
            "Bill of Materials",
            "Render Studio",
            "Global Interference / Clash Check"
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 20,
        "question": "In Creo Sheetmetal design, what parameter represents the ratio of the neutral axis position to the sheet metal thickness during bending?",
        "options": [
            "Poisson's Ratio",
            "Shear Modulus",
            "K-Factor",
            "Young's Modulus"
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 21,
        "question": "Which Creo Sheetmetal feature is used to unbend a formed sheetmetal part into its flat layout state?",
        "options": [
            "Extrude Cut",
            "Rip",
            "Form",
            "Flat Pattern / Unbend"
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 22,
        "question": "What is the primary file extension for a single 3D solid part model in PTC Creo?",
        "options": [
            ".prt",
            ".sec",
            ".asm",
            ".drw"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 23,
        "question": "What is the primary file extension for an Assembly model in PTC Creo?",
        "options": [
            ".asm",
            ".prt",
            ".frm",
            ".drw"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 24,
        "question": "How does Creo handle file versioning when saving a model repeatedly (e.g., saving `bracket.prt`)?",
        "options": [
            "Renames the file to read-only",
            "Compresses the file into a zip archive",
            "Appends an incremental version number extension (e.g., `bracket.prt.1`, `bracket.prt.2`)",
            "Overwrites the previous file with no backup"
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 25,
        "question": "In Creo Drawing (.drw), what functionality is used to automatically generate an associative Bill of Materials (BOM) table?",
        "options": [
            "Repeat Region in Table",
            "Screenshot paste",
            "Manual text typing",
            "OLE object insertion"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 26,
        "question": "In engineering drawings, what does a 'Section View' reveal that is not visible in standard exterior projection views?",
        "options": [
            "The total shipping package dimensions",
            "Internal geometry, ribs, holes, and wall thicknesses along a cutting plane",
            "The customer contact address",
            "The external surface finish color"
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 27,
        "question": "In GD&T, what symbol represents the tolerance zone within which the axis of a cylindrical feature must lie relative to datum references?",
        "options": [
            "Flatness",
            "Profile of a line",
            "Straightness",
            "Position (True Position)"
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 28,
        "question": "In Finite Element Analysis (FEA) with Creo Simulate, what are the two fundamental boundary conditions required for a static structural analysis?",
        "options": [
            "Toolpath feed rate and spindle speed",
            "Electrical resistance and capacitance",
            "Constraints (supports) and Loads (forces/pressures)",
            "Fluid viscosity and ambient humidity"
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 29,
        "question": "Which neutral 3D CAD data exchange file format is widely used for sending 3D geometry to manufacturing suppliers with full NURBS boundary representation?",
        "options": [
            "STEP (.stp / .step)",
            "STL (.stl)",
            "MP3 (.mp3)",
            "BMP (.bmp)"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 30,
        "question": "Which standard tessellated mesh file format is universally exported from Creo for rapid prototyping and 3D printing (Additive Manufacturing)?",
        "options": [
            "PDF",
            "STL (Stereolithography)",
            "TIFF",
            "DWG"
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    }
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
