# ============================================================
# MECHANICAL (CREO / 3D CAD) QUESTIONS (Orders 1 - 30)
# ============================================================

MECH_DEPARTMENTS = ["MECH - Creo", "MECH"]

questions = [
    {
        "order": 1,
        "question": "What is PTC Creo primarily categorized as in engineering design?",
        "options": [
            "Parametric 3D CAD / CAM / CAE modeling software",
            "Relational Database Management System",
            "Vector graphic illustration software",
            "Operating system kernel utility"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 2,
        "question": "In Creo Sketcher, what is the key difference between 'Weak' and 'Strong' dimensions?",
        "options": [
            "Weak dimensions are automatically generated by the Intent Manager; Strong dimensions are explicitly defined or modified by the user",
            "Weak dimensions are measured in inches; Strong dimensions are measured in millimeters",
            "Weak dimensions cannot be seen on screen; Strong dimensions are always visible",
            "Weak dimensions apply only to 3D solids; Strong dimensions apply to 2D sketches"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 3,
        "question": "Which tool in Creo is used to create a 3D solid by linearly projecting a 2D sketch perpendicular to the sketch plane?",
        "options": ["Extrude", "Revolve", "Sweep", "Blend"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 4,
        "question": "What essential geometric reference is mandatory when creating a solid feature using the 'Revolve' tool in Creo?",
        "options": [
            "A centerline / Axis of revolution",
            "A spherical datum coordinate",
            "A helical trajectory curve",
            "A chamfer vertex point"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 5,
        "question": "What is the primary function of a 'Datum Plane' in Creo parametric modeling?",
        "options": [
            "Serves as a reference plane for sketching, dimensioning, and feature placement",
            "Defines the raw material cost of the component",
            "Specifies the thermal conductivity of the alloy",
            "Renders photorealistic raytraced textures"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 6,
        "question": "Which tool in Creo creates a solid feature by sweeping a planar cross-section along an open or closed trajectory path?",
        "options": ["Sweep", "Extrude", "Hole", "Shell"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 7,
        "question": "What is the engineering purpose of applying a 'Round' (Fillet) to the re-entrant corners of a mechanical part?",
        "options": [
            "To reduce stress concentrations and eliminate notch effects",
            "To increase the structural weight of the casting",
            "To make the CAD file size smaller",
            "To speed up 3D printing slicing"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 8,
        "question": "Which dimension scheme option is available when defining a standard 'Chamfer' in Creo?",
        "options": [
            "45 x D, D x D, D1 x D2, and Angle x D",
            "Radius x Arc Length only",
            "Diameter x Pitch only",
            "Volume x Density"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 9,
        "question": "In Creo, which feature is used to hollow out the interior of a solid body while maintaining specified wall thickness?",
        "options": ["Shell", "Rib", "Draft", "Mirror"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 10,
        "question": "Why is a 'Draft' feature applied to faces of components designed for plastic injection molding or metal casting?",
        "options": [
            "To provide a taper angle allowing easy ejection of the part from the mold",
            "To increase the hardness of the plastic resin",
            "To prevent oxidation of the mold steel",
            "To convert 3D geometry into 2D drawing lines"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 11,
        "question": "Which Creo feature is specifically engineered for adding structural stiffening webs between intersecting walls?",
        "options": ["Rib (Profile Rib / Trajectory Rib)", "Extrude Cut", "Chamfer", "Datum Axis"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 12,
        "question": "What are the standard hole creation types provided by the Creo 'Hole' tool?",
        "options": [
            "Simple, Standard (Threaded/Clearance), and Sketched",
            "Square, Hexagonal, and Octagonal only",
            "Punched and Laser cut only",
            "Magnetic and Hydraulic"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 13,
        "question": "Which pattern type in Creo allows replicating features radially around a central cylindrical axis?",
        "options": ["Axis Pattern", "Direction Pattern", "Fill Pattern", "Table Pattern"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 14,
        "question": "In Creo, what capability do 'Relations' (Tools > Relations) provide in parametric modeling?",
        "options": [
            "Mathematical equations that drive dimensions based on other dimensions or parameters",
            "Bluetooth connections to CNC machines",
            "Email notifications when a file is saved",
            "Automatic color grading of 3D models"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 15,
        "question": "What is a 'Family Table' in Creo used for?",
        "options": [
            "Generating a collection of similar parts (instances) derived from a single generic model",
            "Managing user accounts and employee salaries",
            "Organizing computer hard drive directories",
            "Arranging color palettes in the rendering module"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 16,
        "question": "In Creo Assembly, which constraint aligns two planar faces so that their normal vectors point in opposite directions and touch?",
        "options": ["Mate", "Align", "Insert", "Orient"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 17,
        "question": "Which Creo Assembly constraint is commonly used to assemble a bolt or pin into a cylindrical hole in one step?",
        "options": ["Insert", "Tangent", "Fix", "Parallel"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 18,
        "question": "In Creo Mechanism Design, which connection joint allows pure rotational movement around a single axis (1 degree of freedom)?",
        "options": ["Pin joint", "Slider joint", "Cylinder joint", "Ball joint"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 19,
        "question": "What tool in Creo Assembly is utilized to identify physical overlapping between neighboring solid components?",
        "options": [
            "Global Interference / Clash Check",
            "Bill of Materials",
            "Explode State animation",
            "Render Studio"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 20,
        "question": "In Creo Sheetmetal design, what parameter represents the ratio of the neutral axis position to the sheet metal thickness during bending?",
        "options": ["K-Factor", "Young's Modulus", "Poisson's Ratio", "Shear Modulus"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 21,
        "question": "Which Creo Sheetmetal feature is used to unbend a formed sheetmetal part into its flat layout state?",
        "options": ["Flat Pattern / Unbend", "Extrude Cut", "Rip", "Form"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 22,
        "question": "What is the primary file extension for a single 3D solid part model in PTC Creo?",
        "options": [".prt", ".asm", ".drw", ".sec"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 23,
        "question": "What is the primary file extension for an Assembly model in PTC Creo?",
        "options": [".asm", ".prt", ".drw", ".frm"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 24,
        "question": "How does Creo handle file versioning when saving a model repeatedly (e.g., saving `bracket.prt`)?",
        "options": [
            "Appends an incremental version number extension (e.g., `bracket.prt.1`, `bracket.prt.2`)",
            "Overwrites the previous file with no backup",
            "Compresses the file into a zip archive",
            "Renames the file to read-only"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 25,
        "question": "In Creo Drawing (.drw), what functionality is used to automatically generate an associative Bill of Materials (BOM) table?",
        "options": [
            "Repeat Region in Table",
            "OLE object insertion",
            "Manual text typing",
            "Screenshot paste"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 26,
        "question": "In engineering drawings, what does a 'Section View' reveal that is not visible in standard exterior projection views?",
        "options": [
            "Internal geometry, ribs, holes, and wall thicknesses along a cutting plane",
            "The external surface finish color",
            "The total shipping package dimensions",
            "The customer contact address"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 27,
        "question": "In GD&T, what symbol represents the tolerance zone within which the axis of a cylindrical feature must lie relative to datum references?",
        "options": ["Position (True Position)", "Flatness", "Straightness", "Profile of a line"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 28,
        "question": "In Finite Element Analysis (FEA) with Creo Simulate, what are the two fundamental boundary conditions required for a static structural analysis?",
        "options": [
            "Constraints (supports) and Loads (forces/pressures)",
            "Fluid viscosity and ambient humidity",
            "Toolpath feed rate and spindle speed",
            "Electrical resistance and capacitance"
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 29,
        "question": "Which neutral 3D CAD data exchange file format is widely used for sending 3D geometry to manufacturing suppliers with full NURBS boundary representation?",
        "options": ["STEP (.stp / .step)", "STL (.stl)", "BMP (.bmp)", "MP3 (.mp3)"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    },
    {
        "order": 30,
        "question": "Which standard tessellated mesh file format is universally exported from Creo for rapid prototyping and 3D printing (Additive Manufacturing)?",
        "options": ["STL (Stereolithography)", "DWG", "PDF", "TIFF"],
        "correctIndex": 0,
        "marks": 1,
        "departments": MECH_DEPARTMENTS
    }
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)