# ============================================================
# MECHANICAL ENGINEERING - CATIA (DASSAULT SYSTEMES V5)
# 40 Dedicated CAD & Mechanical Aptitude Questions
# ============================================================

DEPARTMENT = "MECH - CATIA"

questions = [
    {
        "order": 1,
        "question": "Why are constraints important in sketches?",
        "options": [
            "Coloring",
            "Accuracy",
            "Rendering",
            "Animation",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 2,
        "question": "Where is Part Design workbench used?",
        "options": [
            "2D Drawing",
            "Surface only",
            "Solid modeling",
            "Animation",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 3,
        "question": "When is Pocket command used?",
        "options": [
            "Adding material",
            "Remove material",
            "Solid modeling",
            "Hole",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 4,
        "question": "How does Pad create geometry?",
        "options": [
            "Cutting",
            "Rotating",
            "Extruding",
            "Sealing",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 5,
        "question": "What is the main purpose of CATIA?",
        "options": [
            "3D Designing",
            "2D Designing",
            "Coding",
            "Surface Modeling",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 6,
        "question": "What is the use of Profile tool in CATIA?",
        "options": [
            "To create 3D objects",
            "To draw sketches",
            "To apply material",
            "To do rendering",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 7,
        "question": "Difference between line and polyline?",
        "options": [
            "Line is single segment, polyline is multiple connected segments",
            "Line is 3D, polyline is 2D",
            "Line is for coloring",
            "No difference",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 8,
        "question": "What is the use of Scale tool?",
        "options": [
            "Move object",
            "Change size bigger",
            "Change size smaller",
            "Increase or decrease size",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 9,
        "question": "Which tool is used to create a spring?",
        "options": [
            "Pad",
            "Multi section",
            "Helix",
            "Rib",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 10,
        "question": "Where do we use multi section feature?",
        "options": [
            "Create shapes with different sections",
            "Constrain sketch",
            "Measurement analysis",
            "Delete objects",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 11,
        "question": "Which tool uses profile and guide curve?",
        "options": [
            "Helix",
            "Multi pocket",
            "Rib",
            "Stiffener",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 12,
        "question": "Primary purpose of Assembly in CATIA?",
        "options": [
            "Modify surface appearance",
            "Combine multiple parts into single product",
            "Generate 2D sketches",
            "All of the above",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 13,
        "question": "In Assembly Design, applying Fix constraint will:",
        "options": [
            "Allow movement",
            "Delete component",
            "Completely lock component",
            "Rotate automatically",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 14,
        "question": "Contact constraint ensures:",
        "options": [
            "Overlap",
            "Surfaces touch without penetration",
            "Parallel components",
            "Rotation",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 15,
        "question": "Shell function:",
        "options": [
            "Remove",
            "Hole",
            "Hollow",
            "Pad",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 16,
        "question": "Shaft command is used when:",
        "options": [
            "Linear extrusion",
            "Surface creation",
            "Assembly",
            "Revolve sketch",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 17,
        "question": "Draft feature is important for:",
        "options": [
            "Molding process",
            "Coloring",
            "Angle Sketch",
            "Drafting",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 18,
        "question": "Rib feature helps to:",
        "options": [
            "Remove material",
            "Add material along path",
            "Fix sketch",
            "Create hole",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 19,
        "question": "Fully constrained sketch means:",
        "options": [
            "No movement possible",
            "Has error",
            "Open sketch",
            "Free to move",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 20,
        "question": "Hole tool allows:",
        "options": [
            "Simple holes only",
            "Surface holes",
            "Assembly holes",
            "Parametric holes",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 21,
        "question": "Coincidence constraint is used to:",
        "options": [
            "align elements.",
            "separate parts.",
            "Rotate parts.",
            "Color parts.",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 22,
        "question": "Contact constraint in assembly ensures:",
        "options": [
            "overlap",
            "Touch",
            "Distance",
            "Rotation",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 23,
        "question": "Offset constraint maintains:",
        "options": [
            "Distance",
            "Angle",
            "Shape",
            "Axis",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 24,
        "question": "Degrees of freedom means:",
        "options": [
            "file size",
            "color",
            "movement",
            "material",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 25,
        "question": "Drafting Workbench used for:",
        "options": [
            "3D modeling.",
            "2D Drawing",
            "offset cut section.",
            "Sketch",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 26,
        "question": "Section views shows:",
        "options": [
            "Internal",
            "External",
            "offset cut section.",
            "Aligned cut section.",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 27,
        "question": "Hidden lines represent:",
        "options": [
            "Visible edges.",
            "Axis",
            "center",
            "Invisible edges.",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 28,
        "question": "Remastering is related to:",
        "options": [
            "Sketch",
            "Boolean",
            "Reverse engineering",
            "STP files",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 29,
        "question": "STL file represents:",
        "options": [
            "mesh",
            "Sketch",
            "Drawing",
            "Geometrical Body",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 30,
        "question": "Boolean add operation used to:",
        "options": [
            "Subtract.",
            "Combine",
            "Rotate",
            "Add material",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 31,
        "question": "Boolean operations need:",
        "options": [
            "One body",
            "Sketch",
            "Two body",
            "Part body",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 32,
        "question": "Blue Sketch indicates:",
        "options": [
            "Fully Constrained",
            "Under Constrained",
            "Error",
            "Fixed",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 33,
        "question": "Sweep requires:",
        "options": [
            "Path + profile",
            "Profile + profile",
            "2 Profile + path",
            "None of the above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 34,
        "question": "Update Command:",
        "options": [
            "Refresh",
            "fix",
            "Lock",
            "ERROR",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 35,
        "question": "Pocket vs Groove:",
        "options": [
            "Linear and rotation",
            "Surface remove",
            "Same",
            "Both a & c",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 36,
        "question": "Constraint error occurs due to:",
        "options": [
            "less constraints",
            "Color",
            "Fully constraint",
            "Conflict",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 37,
        "question": "Catia Software is mainly developed by:",
        "options": [
            "Autodesk",
            "Siemens",
            "PTC",
            "Dassault systems",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 38,
        "question": "Which plane is default for Sketching?",
        "options": [
            "XY, YZ, ZX",
            "only XY",
            "only ZX",
            "Custom only",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 39,
        "question": "Surface Gap repair process",
        "options": [
            "Trim",
            "Offset",
            "Healing",
            "Sweep",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
    {
        "order": 40,
        "question": "Which file is used for 2D Drawing?",
        "options": [
            "CATPart",
            "CATProduct",
            "CATDrawing",
            "STL",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - CATIA", "MECH", "CATIA"],
    },
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
