# ============================================================
# MECHANICAL ENGINEERING - AUTOCAD (AUTODESK 2D/3D CAD)
# 40 Dedicated CAD & Mechanical Aptitude Questions
# ============================================================

DEPARTMENT = "MECH - AutoCAD"

questions = [
    {
        "order": 1,
        "question": "In CAD, the LIMITS command allows you to determine the:",
        "options": [
            "Size of the drawing space",
            "Size of the text",
            "Amount of time that is needed to draw",
            "None of the above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 2,
        "question": "A Uniform pattern of dots/lines on the CAD screen is called as ____________",
        "options": [
            "All of above",
            "Grid",
            "Reference dot pattern",
            "Snap pattern",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 3,
        "question": "What do you mean by AutoCAD?",
        "options": [
            "Automatic Candidate Address Detection",
            "Automatic Card Address Direction",
            "Automatic Computer Active Décor",
            "Automatic Computer-Aided Design/Drafting",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 4,
        "question": "What does CAD in AutoCAD stand for?",
        "options": [
            "Computer Aided Design",
            "Computer Advance Detail",
            "Computer Assignment Description",
            "All of above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 5,
        "question": "Which key can be used to quickly cancel a command?",
        "options": [
            "backspace",
            "esc",
            "tab",
            "enter",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 6,
        "question": "What does UCS means?(In the context of CAD)",
        "options": [
            "User Coordinate System",
            "United CAD Software",
            "United Coordinate System",
            "User CAD Software",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 7,
        "question": "What are the characteristics of a Triangle?",
        "options": [
            "2 sides, 4 angles",
            "4 sides, 4 angles",
            "4 sides, 3 angles",
            "3 sides, 3 angles",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 8,
        "question": "The command for opening 'drawing units' window is",
        "options": [
            "U",
            "UN",
            "UNI",
            "UNIT",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 9,
        "question": "A command used to check a distance _____________",
        "options": [
            "fillet",
            "offset",
            "pan",
            "dist",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 10,
        "question": "What does the Offset command do?",
        "options": [
            "Moves to specified distance",
            "Moves above specified distance",
            "Moves away from specified distance",
            "None of the above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 11,
        "question": "Where would AutoCAD ask you for something?",
        "options": [
            "Tool Icons",
            "Command Line",
            "Properties Palette",
            "Toolbar",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 12,
        "question": "The shortcut for using Zoom command is",
        "options": [
            "Z Command",
            "Rotate mouse wheel",
            "ZOOM Command",
            "All of the above",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 13,
        "question": "In Cartesian coordinate system, the axis is vertical.",
        "options": [
            "X",
            "Y",
            "Z",
            "W",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 14,
        "question": "If AutoCAD is displaying length of a line as 24.952 then what is the precision selected?",
        "options": [
            "(0.0)",
            "(0.00)",
            "(0.000)",
            "Display of length has nothing to do with precision",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 15,
        "question": "When saving your drawings in AutoCAD the default file type is...?",
        "options": [
            "pdf",
            "dwg",
            "bak",
            "doc",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 16,
        "question": "What does the command Fillet do?",
        "options": [
            "Straightens an angle",
            "Curves an angle",
            "Deletes an angle",
            "All of above",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 17,
        "question": "The shortcut command key for UNDO",
        "options": [
            "CTRL+C",
            "CTRL+Z",
            "CTRL+CU",
            "CTRL+CHA",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 18,
        "question": "The shortcut command key for TABLE",
        "options": [
            "TL",
            "TE",
            "TN",
            "TB",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 19,
        "question": "Which option will you use to make a circle which is tangent to a line and circle and has certain radius value",
        "options": [
            "2 Point circle",
            "3 Point circle",
            "Tangent, tangent, radius circle",
            "Tangent, tangent, tangent circle",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 20,
        "question": "The ____________ command is used to lengthen a line to meet an edge.",
        "options": [
            "Array",
            "Chamfer",
            "Extend",
            "Rotate",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 21,
        "question": "Is it possible to make a rectangle with fillets on all four vertices?",
        "options": [
            "Yes",
            "No",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 22,
        "question": "Can you use Polygon tool to make a polygon with a known edge length without using inscribed or circumscribed circle as a reference?",
        "options": [
            "Yes",
            "No",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 23,
        "question": "State true or false: It is not possible to make a linear array with copy command",
        "options": [
            "True",
            "False",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 24,
        "question": "Which CAD command enlarges or reduces selected objects proportionally in the X, Y, and Z directions from a base point?",
        "options": [
            "Stretch",
            "Divide",
            "Array",
            "Scale",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 25,
        "question": "Which CAD command creates multiple copies of objects in a circular or rectangular pattern?",
        "options": [
            "Array",
            "Extend",
            "Chamfer",
            "Rotate",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 26,
        "question": "The ___________ command provides the length of an object but does not place a dimension line on the drawing?",
        "options": [
            "Annotate",
            "Leader",
            "Baseline",
            "Distance",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 27,
        "question": "CAD commands such as LINE, CIRCLE, and ARC and other basic CAD figures are examples of ____________",
        "options": [
            "Modify commands",
            "Edit commands",
            "Draw commands",
            "None of the above",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 28,
        "question": "How many AutoCAD OBJECTS are in a rectangle?",
        "options": [
            "One",
            "Two",
            "Four",
            "None of above",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 29,
        "question": "To reduce the size of an object to half of its initial value using SCALE command the scale factor would be?",
        "options": [
            "2",
            "0.25",
            "0.5",
            "4",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 30,
        "question": "Which function key enables object snap in AutoCAD?",
        "options": [
            "F2",
            "F3",
            "F5",
            "F8",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 31,
        "question": "Which factor of hatch command you will change to correct the spacing between hatch lines or pattern",
        "options": [
            "Pattern",
            "Angle",
            "Scale",
            "Layer",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 32,
        "question": "The __________ tool is used to fill in an object with color/pattern design.",
        "options": [
            "Arc",
            "Hatch",
            "Line",
            "Pattern",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 33,
        "question": "What a break line used for?",
        "options": [
            "To show an alternate position",
            "To represent an edge not visible",
            "To represent a line of symmetry",
            "To eliminate a section of drawing not needed because of size",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 34,
        "question": "The origin of a drawing is ALWAYS at _____________",
        "options": [
            "0,0",
            "The first point you select",
            "A random point In space",
            "UCS ICON",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 35,
        "question": "Polar coordinates are used mostly for drawing __________",
        "options": [
            "Arcs",
            "Circles",
            "Angled lines",
            "Vertical and Horizontal Straight Lines",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 36,
        "question": "The ___________ command will adjust the display so that all objects in the drawing are displayed to be as large as possible.",
        "options": [
            "Pan",
            "Circle",
            "Zoom All",
            "Orbit",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 37,
        "question": "What is the difference between command Plot and Print?",
        "options": [
            "Print command can print up to A3 size paper",
            "Plot command prints only big plans",
            "The plot command for CNC(CAM)",
            "No difference",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 38,
        "question": "From which direction does AutoCAD start measuring angles?",
        "options": [
            "6 o'clock",
            "9 o'clock",
            "3 o'clock",
            "12 o'clock",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 39,
        "question": "To break a Poly line into lines and arcs which command can be used",
        "options": [
            "BREAК",
            "TRIM",
            "EXPLODE",
            "OVERKILL",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
    {
        "order": 40,
        "question": "How many points do you need to define for the rectangle command?",
        "options": [
            "Two",
            "Four",
            "One",
            "None",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": ["MECH - AutoCAD", "MECH", "AutoCAD", "Auto CAD"],
    },
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
