# ============================================================
# SAP MM (MATERIALS MANAGEMENT)
# 30 Dedicated Technical Multiple Choice Questions (Order 1-30)
# ============================================================

DEPARTMENT = "SAP - SAP MM"
DEPARTMENTS = ["SAP - SAP MM", "SAP - MM", "SAP MM", "MM"]



questions = [
    {
        "order": 1,
        "question": "What does P2P stand for?",
        "options": [
            "Plan to Product",
            "Procure to Pay",
            "Purchase to Production",
            "Product to Payment",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 2,
        "question": "Which T-code is used to create a Purchase Requisition?",
        "options": [
            "ME21N",
            "ME51N",
            "MIGO",
            "MIRO",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 3,
        "question": "Which T-code is used to create a Purchase Order?",
        "options": [
            "ME21N",
            "ME51N",
            "ME41",
            "MIRO",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 4,
        "question": "Which T-code is used to display a Purchase Order?",
        "options": [
            "ME22N",
            "ME23N",
            "ME51N",
            "ME11",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 5,
        "question": "Which T-code is used to change a Purchase Order?",
        "options": [
            "ME21N",
            "ME22N",
            "ME23N",
            "ME52N",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 6,
        "question": "Which T-code is used to create an RFQ?",
        "options": [
            "ME41",
            "ME49",
            "ME11",
            "ME01",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 7,
        "question": "What is the purpose of an RFQ?",
        "options": [
            "To receive materials",
            "To request price quotations from vendors",
            "To post an invoice",
            "To make payment",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 8,
        "question": "Which T-code is used to compare vendor quotations?",
        "options": [
            "ME41",
            "ME49",
            "ME21N",
            "MIGO",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 9,
        "question": "Which T-code is used to create a Purchase Info Record?",
        "options": [
            "ME01",
            "ME11",
            "ME21N",
            "ME51N",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 10,
        "question": "What does a Purchase Info Record contain?",
        "options": [
            "Customer information",
            "Material and vendor purchasing information",
            "Employee information",
            "Company code information",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 11,
        "question": "Which T-code is used to maintain a Source List?",
        "options": [
            "ME01",
            "ME11",
            "ME41",
            "ME49",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 12,
        "question": "What is a Purchase Requisition?",
        "options": [
            "Vendor invoice",
            "Internal request to purchase materials or services",
            "Goods receipt",
            "Payment document",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 13,
        "question": "What is a Purchase Order?",
        "options": [
            "Internal request",
            "Official purchasing document sent to the vendor",
            "Customer invoice",
            "Goods issue document",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 14,
        "question": "Which T-code is commonly used for Goods Receipt?",
        "options": [
            "MIRO",
            "MIGO",
            "ME21N",
            "ME51N",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 15,
        "question": "Which movement type is used for standard Goods Receipt against a PO?",
        "options": [
            "101",
            "102",
            "122",
            "201",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 16,
        "question": "Which movement type is used to reverse a 101 Goods Receipt?",
        "options": [
            "102",
            "101",
            "122",
            "161",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 17,
        "question": "What is Goods Receipt?",
        "options": [
            "Sending materials to vendor",
            "Receiving materials from vendor",
            "Creating a quotation",
            "Making payment",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 18,
        "question": "Which T-code is used for Invoice Verification?",
        "options": [
            "MIGO",
            "MIRO",
            "ME23N",
            "ME51N",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 19,
        "question": "What is a 3-way match?",
        "options": [
            "PR, RFQ and PO",
            "PO, GR and Invoice",
            "PO, Payment and Vendor",
            "PR, GR and Payment",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 20,
        "question": "Which document is normally created after receiving materials?",
        "options": [
            "Goods Receipt document",
            "RFQ",
            "Purchase Requisition",
            "Quotation",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 21,
        "question": "Who usually provides the quotation?",
        "options": [
            "Customer",
            "Vendor",
            "Employee",
            "Production department",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 22,
        "question": "Which organizational unit is responsible for purchasing activities?",
        "options": [
            "Plant",
            "Purchasing Organization",
            "Storage Location",
            "Company Code",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 23,
        "question": "What is a Purchasing Group?",
        "options": [
            "Group of materials",
            "Buyer or group of buyers responsible for purchasing",
            "Group of vendors",
            "Group of plants",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 24,
        "question": "Which master data contains material information?",
        "options": [
            "Material Master",
            "Vendor Master",
            "Customer Master",
            "Bank Master",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 25,
        "question": "Which master data contains vendor purchasing information?",
        "options": [
            "Material Master",
            "Vendor/Business Partner",
            "Customer Master",
            "Asset Master",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 26,
        "question": "What is a Source List used for?",
        "options": [
            "To identify valid sources/vendors for procurement",
            "To create invoices",
            "To receive materials",
            "To make payments",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 27,
        "question": "What is the correct basic P2P sequence?",
        "options": [
            "PO → PR → GR → Invoice",
            "PR → PO → GR → Invoice",
            "GR → PR → PO → Invoice",
            "Invoice → PO → PR → GR",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 28,
        "question": "Which document is sent officially to the vendor to purchase materials?",
        "options": [
            "PR",
            "PO",
            "GR",
            "Invoice",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 29,
        "question": "Which department is mainly responsible for purchasing activities?",
        "options": [
            "Purchasing/Procurement",
            "Production",
            "Sales",
            "Human Resources",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 30,
        "question": "What is the final stage of the P2P process?",
        "options": [
            "Purchase Requisition",
            "Goods Receipt",
            "Invoice Verification",
            "Vendor Payment",
        ],
        "correctIndex": 3,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
