# ============================================================
# SAP FICO (FINANCIAL ACCOUNTING & CONTROLLING)
# 30 Dedicated Technical Multiple Choice Questions (Order 1-30)
# ============================================================

DEPARTMENT = "SAP - SAP FICO"
DEPARTMENTS = ["SAP - SAP FICO", "SAP - FICO", "SAP FICO", "FICO"]

questions = [
    {
        "order": 1,
        "question": "What does FI stand for in SAP?",
        "options": [
            "Financial Integration",
            "Financial Accounting",
            "Finance Information",
            "Financial Interface",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 2,
        "question": "What does CO stand for in SAP?",
        "options": [
            "Cost Operations",
            "Controlling",
            "Company Operations",
            "Corporate Accounting",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 3,
        "question": "Which organizational unit is used for external accounting in SAP?",
        "options": [
            "Plant",
            "Company Code",
            "Purchasing Organization",
            "Sales Organization",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 4,
        "question": "Which T-code is commonly used to create a G/L account centrally?",
        "options": [
            "FS00",
            "FB50",
            "F-02",
            "FBL3N",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 5,
        "question": "Which T-code is used to post a G/L document?",
        "options": [
            "FB60",
            "FB70",
            "F-02",
            "F-53",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 6,
        "question": "Which T-code is used to post a vendor invoice?",
        "options": [
            "FB60",
            "FB70",
            "F-28",
            "F-53",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 7,
        "question": "Which T-code is used to post a customer invoice?",
        "options": [
            "FB60",
            "FB70",
            "F-53",
            "F-44",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 8,
        "question": "Which T-code is used for outgoing vendor payment?",
        "options": [
            "F-28",
            "F-53",
            "FB70",
            "F-32",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 9,
        "question": "Which T-code is used for incoming customer payment?",
        "options": [
            "F-28",
            "F-53",
            "FB60",
            "F-44",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 10,
        "question": "Which T-code is used to display a G/L account line-item list in classic SAP?",
        "options": [
            "FBL1N",
            "FBL3N",
            "FBL5N",
            "FS00",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 11,
        "question": "Which T-code is used to display vendor line items?",
        "options": [
            "FBL1N",
            "FBL3N",
            "FBL5N",
            "FB60",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 12,
        "question": "Which T-code is used to display customer line items?",
        "options": [
            "FBL1N",
            "FBL3N",
            "FBL5N",
            "FB70",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 13,
        "question": "What is Accounts Payable (AP)?",
        "options": [
            "Accounting for customers",
            "Accounting for vendors",
            "Accounting for assets only",
            "Accounting for banks only",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 14,
        "question": "What is Accounts Receivable (AR)?",
        "options": [
            "Accounting for vendors",
            "Accounting for customers",
            "Accounting for employees",
            "Accounting for assets",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 15,
        "question": "What is a Chart of Accounts?",
        "options": [
            "List of vendors",
            "List of customers",
            "Structure containing G/L accounts",
            "List of company codes",
        ],
        "correctIndex": 2,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 16,
        "question": "What is a Fiscal Year Variant?",
        "options": [
            "Defines fiscal year and posting periods",
            "Defines vendor groups",
            "Defines payment methods only",
            "Defines material types",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 17,
        "question": "What is a Posting Period Variant?",
        "options": [
            "Controls which periods are open for posting",
            "Creates company codes",
            "Creates vendors",
            "Maintains exchange rates",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 18,
        "question": "What is a Document Type in SAP FI?",
        "options": [
            "Identifies the nature/type of accounting document",
            "Identifies a material",
            "Identifies a vendor address",
            "Identifies a plant",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 19,
        "question": "What is a Business Partner in SAP S/4HANA?",
        "options": [
            "Only a material",
            "A central master object for customers and vendors",
            "Only a G/L account",
            "A company code",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 20,
        "question": "What is Cost Center Accounting used for?",
        "options": [
            "Tracking costs by organizational area",
            "Creating customer invoices",
            "Managing purchase orders",
            "Managing stock quantities",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 21,
        "question": "Which T-code is commonly used to create a cost center?",
        "options": [
            "KS01",
            "KO01",
            "FB01",
            "FS00",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 22,
        "question": "Which T-code is commonly used to create an internal order?",
        "options": [
            "KS01",
            "KO01",
            "KSB1",
            "FB50",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 23,
        "question": "What is a Profit Center?",
        "options": [
            "Organizational unit used to analyze profitability",
            "Vendor account",
            "Customer account",
            "Material type",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 24,
        "question": "What is an Asset in SAP FI-AA?",
        "options": [
            "A long-term company resource",
            "A vendor invoice",
            "A customer payment",
            "A purchase requisition",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 25,
        "question": "What is depreciation?",
        "options": [
            "Increase in asset value",
            "Allocation of an asset's depreciable value over its useful life",
            "Vendor payment",
            "Customer receipt",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 26,
        "question": "What is a Bank Reconciliation process?",
        "options": [
            "Comparing bank records with company accounting records",
            "Creating a purchase order",
            "Creating a material",
            "Creating a cost center",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 27,
        "question": "What is a Financial Statement?",
        "options": [
            "Report showing financial position/performance",
            "Vendor master record",
            "Purchase order",
            "Material document",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 28,
        "question": "What is the purpose of a payment term?",
        "options": [
            "Defines conditions and due dates for payment",
            "Creates a G/L account",
            "Creates a plant",
            "Determines material price",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 29,
        "question": "What is a Clearing Document?",
        "options": [
            "Document created when open items are cleared",
            "Material master document",
            "Purchase order document",
            "Sales order document",
        ],
        "correctIndex": 0,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
    {
        "order": 30,
        "question": "Which two major areas are covered by SAP FICO?",
        "options": [
            "MM and SD",
            "FI and CO",
            "PP and PM",
            "WM and EWM",
        ],
        "correctIndex": 1,
        "marks": 1,
        "departments": DEPARTMENTS,
    },
]

if __name__ == "__main__":
    from upload import upload_questions
    upload_questions(questions)
